export type { ApiErrorBody, ErrorCode } from "./errors";
export { apiError, isApiErrorBody } from "./errors";
export { isSha256, sha256Hex, toHex } from "./hash";
export {
  ACCESS_TOKEN_WARNING_MS,
  BIND_CHUNK,
  COMMIT_MAX_CHANGES,
  D1_NOTICE_BYTES,
  D1_WARNING_BYTES,
  DESKTOP_BYTE_BUDGET,
  EMPTY_FILE_GUARD_BYTES,
  EXISTS_MAX_SHA256S,
  GC_MIN_AGE_MS,
  HISTORY_MIN_REVISIONS,
  HISTORY_RETENTION_MS,
  INDEX_PAGE_SIZE,
  LAST_SEEN_UPDATE_INTERVAL_MS,
  MAINTENANCE_RETRY_AFTER_SECONDS,
  MAINTENANCE_STALE_MS,
  MAX_FILE_BYTES,
  MAX_RETRY_WINDOW_MS,
  MAX_SYNC_ATTEMPTS,
  MOBILE_BYTE_BUDGET,
  MULTIPART_PART_BYTES,
  PURGE_TOKEN_TTL_MS,
  R2_NOTICE_BYTES,
  RANGE_CHUNK_BYTES,
  REQUEST_RETENTION_MS,
  RESOLVED_CONFLICT_RETENTION_MS,
  SINGLE_PUT_MAX_BYTES,
  TRANSFER_CONCURRENCY,
} from "./limits";
export {
  InvalidPathError,
  isPortablePath,
  isValidPath,
  normalizePath,
  parentPath,
  pathBasename,
  toPathKey,
  validatePath,
} from "./path";
export type {
  BulkGuardThresholds,
  DeviceSettings,
  SharedSettings,
  SnapshotRetention,
} from "./settings";
export {
  DEFAULT_DEVICE_SETTINGS,
  DEFAULT_SHARED_SETTINGS,
  parseDeviceSettings,
  parseSharedSettings,
  SharedSettingsError,
} from "./settings";
export { generateDeviceToken } from "./token";
export type {
  CommitRejection,
  CommitRequest,
  CommitResponse,
  ConflictCreateRequest,
  ConflictRecord,
  CreateSnapshotRequest,
  CreateSnapshotResponse,
  DeviceSummary,
  ExistsRequest,
  ExistsResponse,
  FileChange,
  HealthResponse,
  HistoryEntry,
  HistoryRequest,
  IndexEntry,
  IndexResponse,
  LogEntry,
  LogHighlight,
  LogResponse,
  MaintenanceKind,
  MaintenanceReport,
  PurgePrepareRequest,
  PurgePrepareResponse,
  PurgeRequest,
  PurgeResponse,
  RejectReason,
  ResolveConflictRequest,
  RestoreRequest,
  SnapshotDocument,
  SnapshotFile,
  SnapshotListItem,
  SnapshotOrigin,
  SyncMode,
  UploadCreateRequest,
  UploadCreateResponse,
} from "./types";
export { isContentChange } from "./types";
export {
  API_VERSION,
  apiVersionRange,
  isSupportedApiVersion,
  MIN_SUPPORTED_API_VERSION,
} from "./version";
